import { NextPage } from "next";
import Head from 'next/head'

interface Props {
    userAgent?: string;
}

const Home: NextPage<Props> = ({ userAgent }) => {
    return (
        <Head>
            <title>Pulse</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="css/animate.css/animate.min.css" type="text/css" />
            <link rel="stylesheet" href="css/glyphicons/glyphicons.css" type="text/css" />
            <link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css" type="text/css" />
            <link rel="stylesheet" href="css/material-design-icons/material-design-icons.css" type="text/css" />
            <link rel="stylesheet" href="css/bootstrap/dist/css/bootstrap.min.css" type="text/css" />

            <link rel="stylesheet" href="css/styles/app.css" type="text/css" />
            <link rel="stylesheet" href="css/styles/style.css" type="text/css" />
            <link rel="stylesheet" href="css/styles/font.css" type="text/css" />
        </Head>
    )
}

Home.getInitialProps = async ({ req }) => {
    const userAgent = req ? req.headers['user-agent'] : navigator.userAgent
    return { userAgent, statusCode: 200 }
}

export default Home;